apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.secretName }}
type: Opaque
data:
  {{ .Values.env.secretKey }}: {{ .Values.env.secretValue | b64enc | quote }}
# stringData:
#   {{ .Values.env.secretKey }}: {{ .Values.env.secretValue | quote }}